var num1=10;
var num2=20;
console.log(num1+num2);
console.log(num1-num2);
console.log(num1*num2);
console.log(num2/num1);
console.log(num2%num1);
console.log(10<20);
console.log(10>20);
console.log(true&false);
console.log(true^false);
console.log(true^true);
console.log(true^false);